spring:
  profiles:
    active: local

database:
  master:
    url: jdbc:mysql://localhost:3306/reservation_delegator?characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: 1234
    connection-timeout: 5000
    max-connection: 5
    min-connection: 1
    idle-timeout: 5000
    read-only: false
  slave:
    url: jdbc:mysql://localhost:3306/reservation_delegator?characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: 1234
    connection-timeout: 5000
    max-connection: 5
    min-connection: 1
    idle-timeout: 5000
    read-only: true


---

spring:
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1

